name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v3
      
      # Setup Node.js environment; not strictly necessary if using withastro/action, but included for clarity and control
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install dependencies and build the site
        run: |
          yarn install
          yarn build
        # If your Astro project is not at the root, add 'working-directory: your/project/path' here

      - name: Create .nojekyll file
        run: touch ./dist/.nojekyll
        # Adjust './dist' if your build output directory is different

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages  # The branch you are deploying to
          folder: dist      # The folder the action should deploy
          token: ${{ secrets.GITHUB_TOKEN }}
