name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Ensure you're using the Node version compatible with your project

      - name: Install, build, and upload your site
        uses: withastro/action@v0
        with:
          node-version: '16' # Specify the node version if not the default
          # You can specify a package-manager if your project uses 'npm', 'yarn', or 'pnpm'. If not specified, it will be auto-detected.
          package-manager: 'npm' # Replace 'npm' with your project's package manager, or remove this line if you want auto-detection.
          # If your project is not in the repository root, specify the path, otherwise, this can be omitted.
          # path: '.' # Uncomment and adjust if your project is not in the root of your repository

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
