name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [main] # Set to your default branch
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Specify your Node.js version

    - name: Install Dependencies
      run: npm install

    - name: Build Project
      run: npm run build # Your build command here

    - name: Create .nojekyll File
      run: touch ./dist/.nojekyll # Ensure this matches your build output directory

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: dist # The folder the action should deploy.
        token: ${{ secrets.GITHUB_TOKEN }} # GitHub automatically creates a GITHUB_TOKEN secret to use in your workflow.
